version: '3.9'

services:

  notification-service:
    build: .
    container_name: notification-service

    ports:
      - "8086:8086"

    env_file:
      - .env

    depends_on:
      - mongodb

    restart: never

  mongodb:
    image: mongo:7

    container_name: notification-mongodb

    ports:
      - "27017:27017"

    volumes:
      - mongodb_data:/data/db

    restart: never

volumes:
  mongodb_data: